spring:
  datasource:
    # hikari ?? ??? ????
    hikari:
      # ??? H2 DB? ?? URL
      # ?? ??? in-memory database? ?? ????? ??? ???? ??? ????. ?? ??? ????.
      # ;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      # springboot 2.4 ??? username ? ? ??????. ??? ??? ?????.
      username: sa
      password:
  jpa:
    # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none
    # ????? ??? create ? ????
    # ???? none ?? ???. create ?? ??? ???? ?? ??????.
    hibernate:
      ddl-auto: create-drop
    # JPA ? ???? SQL ? ? ? ??.
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  # ?? ?? ? ?? always
  output:
    ansi:
      enabled: always
# ???? ??? ?? trace
logging:
  level:
    org.hibernate.type: info
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html


